---
name: Semantic Release

on:
    push:
        branches:
            - production
jobs:
    release:
        runs-on: ubuntu-latest
        concurrency: release
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: relekang/python-semantic-release@master
            - name: Semantic Release
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  repository_username: __token__
                  repository_password: ${{ secrets.PYPI_TOKEN }}
